///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace poctest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the poctestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("eb8235e8-0290-4ca7-b360-4472f1905b1b")]
    public partial class poctestRepository : RepoGenBaseFolder
    {
        static poctestRepository instance = new poctestRepository();
        poctestRepositoryFolders.AmazonComOnlineShoppingForElectronAppFolder _amazoncomonlineshoppingforelectron;

        /// <summary>
        /// Gets the singleton class instance representing the poctestRepository element repository.
        /// </summary>
        [RepositoryFolder("eb8235e8-0290-4ca7-b360-4472f1905b1b")]
        public static poctestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public poctestRepository() 
            : base("poctestRepository", "/", null, 0, false, "eb8235e8-0290-4ca7-b360-4472f1905b1b", ".\\RepositoryImages\\poctestRepositoryeb8235e8.rximgres")
        {
            _amazoncomonlineshoppingforelectron = new poctestRepositoryFolders.AmazonComOnlineShoppingForElectronAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("eb8235e8-0290-4ca7-b360-4472f1905b1b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The AmazonComOnlineShoppingForElectron folder.
        /// </summary>
        [RepositoryFolder("4f5e1439-fde2-4ead-9441-3d2fb6be71b8")]
        public virtual poctestRepositoryFolders.AmazonComOnlineShoppingForElectronAppFolder AmazonComOnlineShoppingForElectron
        {
            get { return _amazoncomonlineshoppingforelectron; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class poctestRepositoryFolders
    {
        /// <summary>
        /// The AmazonComOnlineShoppingForElectronAppFolder folder.
        /// </summary>
        [RepositoryFolder("4f5e1439-fde2-4ead-9441-3d2fb6be71b8")]
        public partial class AmazonComOnlineShoppingForElectronAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _signinInfo;
            RepoItemInfo _starthereInfo;
            RepoItemInfo _continueInfo;

            /// <summary>
            /// Creates a new AmazonComOnlineShoppingForElectron  folder.
            /// </summary>
            public AmazonComOnlineShoppingForElectronAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AmazonComOnlineShoppingForElectron", "/dom[@domain='www.amazon.com']", parentFolder, 30000, null, false, "4f5e1439-fde2-4ead-9441-3d2fb6be71b8", "")
            {
                _signinInfo = new RepoItemInfo(this, "SignIn", ".//div[#'nav-flyout-ya-signin']/?/?/span[@innertext='Sign in']", 30000, null, "505c7524-dce6-4add-9da2-5775dd0e1e0a");
                _starthereInfo = new RepoItemInfo(this, "StartHere", ".//div[#'nav-flyout-ya-newCust']/a[@innertext='Start here.']", 30000, null, "864ec229-0216-496c-ad2d-05c92de98d0b");
                _continueInfo = new RepoItemInfo(this, "Continue", ".//span[#'continue']/?/?/input[@id='continue']", 30000, null, "25078f2d-277a-42a3-97ec-3a8005797d18");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f5e1439-fde2-4ead-9441-3d2fb6be71b8")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f5e1439-fde2-4ead-9441-3d2fb6be71b8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SignIn item.
            /// </summary>
            [RepositoryItem("505c7524-dce6-4add-9da2-5775dd0e1e0a")]
            public virtual Ranorex.SpanTag SignIn
            {
                get
                {
                    return _signinInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SignIn item info.
            /// </summary>
            [RepositoryItemInfo("505c7524-dce6-4add-9da2-5775dd0e1e0a")]
            public virtual RepoItemInfo SignInInfo
            {
                get
                {
                    return _signinInfo;
                }
            }

            /// <summary>
            /// The StartHere item.
            /// </summary>
            [RepositoryItem("864ec229-0216-496c-ad2d-05c92de98d0b")]
            public virtual Ranorex.ATag StartHere
            {
                get
                {
                    return _starthereInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The StartHere item info.
            /// </summary>
            [RepositoryItemInfo("864ec229-0216-496c-ad2d-05c92de98d0b")]
            public virtual RepoItemInfo StartHereInfo
            {
                get
                {
                    return _starthereInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("25078f2d-277a-42a3-97ec-3a8005797d18")]
            public virtual Ranorex.InputTag Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("25078f2d-277a-42a3-97ec-3a8005797d18")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
