///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("2aeebb93-73bd-4785-9653-d4711c1c4a19")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        MyTestRepositoryFolders.HowToWriteCodeInCHashRanorexGooAppFolder _howtowritecodeinchashranorexgoo;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("2aeebb93-73bd-4785-9653-d4711c1c4a19")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "2aeebb93-73bd-4785-9653-d4711c1c4a19", ".\\RepositoryImages\\MyTestRepository2aeebb93.rximgres")
        {
            _applicationundertest = new MyTestRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _howtowritecodeinchashranorexgoo = new MyTestRepositoryFolders.HowToWriteCodeInCHashRanorexGooAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("2aeebb93-73bd-4785-9653-d4711c1c4a19")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("3d222afe-3a33-477a-9df3-df2edc2c4aec")]
        public virtual MyTestRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The HowToWriteCodeInCHashRanorexGoo folder.
        /// </summary>
        [RepositoryFolder("657363ab-15e2-480e-b3bc-12236e49e9b4")]
        public virtual MyTestRepositoryFolders.HowToWriteCodeInCHashRanorexGooAppFolder HowToWriteCodeInCHashRanorexGoo
        {
            get { return _howtowritecodeinchashranorexgoo; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("3d222afe-3a33-477a-9df3-df2edc2c4aec")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _apemailInfo;
            RepoItemInfo _continueInfo;
            RepoItemInfo _signinsubmitInfo;
            RepoItemInfo _aalertcontaineraboxinnerInfo;
            RepoItemInfo _appasswordInfo;
            RepoItemInfo _twotabsearchtextboxInfo;
            RepoItemInfo _kurtaInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.amazon.in']", parentFolder, 30000, null, false, "3d222afe-3a33-477a-9df3-df2edc2c4aec", "")
            {
                _apemailInfo = new RepoItemInfo(this, "ApEmail", ".//input[#'ap_email']", 30000, null, "1e646de0-b504-42bd-9d9a-586454a5b791");
                _continueInfo = new RepoItemInfo(this, "Continue", ".//span[#'continue']/?/?/input[@id='continue']", 30000, null, "fd581e22-862c-400c-be0a-81ef17b937bb");
                _signinsubmitInfo = new RepoItemInfo(this, "SignInSubmit", ".//input[#'signInSubmit']", 30000, null, "1134519a-5d67-4247-b688-e16fc0283344");
                _aalertcontaineraboxinnerInfo = new RepoItemInfo(this, "AAlertContainerABoxInner", ".//div[#'auth-error-message-box']/div", 30000, null, "833e2b63-9604-4edd-8c19-21d856f1155a");
                _appasswordInfo = new RepoItemInfo(this, "ApPassword", ".//input[#'ap_password']", 30000, null, "73505b8c-17a0-41d9-8ef9-aa83ae5ec4b5");
                _twotabsearchtextboxInfo = new RepoItemInfo(this, "Twotabsearchtextbox", ".//input[#'twotabsearchtextbox']", 30000, null, "cdbe53c1-b7ab-4689-b256-7090727b7ab3");
                _kurtaInfo = new RepoItemInfo(this, "Kurta", ".//div[#'suggestions']/div[11]", 30000, null, "985e4747-43fd-4c76-a194-08518ca9ee50");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3d222afe-3a33-477a-9df3-df2edc2c4aec")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3d222afe-3a33-477a-9df3-df2edc2c4aec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ApEmail item.
            /// </summary>
            [RepositoryItem("1e646de0-b504-42bd-9d9a-586454a5b791")]
            public virtual Ranorex.InputTag ApEmail
            {
                get
                {
                    return _apemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ApEmail item info.
            /// </summary>
            [RepositoryItemInfo("1e646de0-b504-42bd-9d9a-586454a5b791")]
            public virtual RepoItemInfo ApEmailInfo
            {
                get
                {
                    return _apemailInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("fd581e22-862c-400c-be0a-81ef17b937bb")]
            public virtual Ranorex.InputTag Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("fd581e22-862c-400c-be0a-81ef17b937bb")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The SignInSubmit item.
            /// </summary>
            [RepositoryItem("1134519a-5d67-4247-b688-e16fc0283344")]
            public virtual Ranorex.InputTag SignInSubmit
            {
                get
                {
                    return _signinsubmitInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SignInSubmit item info.
            /// </summary>
            [RepositoryItemInfo("1134519a-5d67-4247-b688-e16fc0283344")]
            public virtual RepoItemInfo SignInSubmitInfo
            {
                get
                {
                    return _signinsubmitInfo;
                }
            }

            /// <summary>
            /// The AAlertContainerABoxInner item.
            /// </summary>
            [RepositoryItem("833e2b63-9604-4edd-8c19-21d856f1155a")]
            public virtual Ranorex.DivTag AAlertContainerABoxInner
            {
                get
                {
                    return _aalertcontaineraboxinnerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The AAlertContainerABoxInner item info.
            /// </summary>
            [RepositoryItemInfo("833e2b63-9604-4edd-8c19-21d856f1155a")]
            public virtual RepoItemInfo AAlertContainerABoxInnerInfo
            {
                get
                {
                    return _aalertcontaineraboxinnerInfo;
                }
            }

            /// <summary>
            /// The ApPassword item.
            /// </summary>
            [RepositoryItem("73505b8c-17a0-41d9-8ef9-aa83ae5ec4b5")]
            public virtual Ranorex.InputTag ApPassword
            {
                get
                {
                    return _appasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ApPassword item info.
            /// </summary>
            [RepositoryItemInfo("73505b8c-17a0-41d9-8ef9-aa83ae5ec4b5")]
            public virtual RepoItemInfo ApPasswordInfo
            {
                get
                {
                    return _appasswordInfo;
                }
            }

            /// <summary>
            /// The Twotabsearchtextbox item.
            /// </summary>
            [RepositoryItem("cdbe53c1-b7ab-4689-b256-7090727b7ab3")]
            public virtual Ranorex.InputTag Twotabsearchtextbox
            {
                get
                {
                    return _twotabsearchtextboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Twotabsearchtextbox item info.
            /// </summary>
            [RepositoryItemInfo("cdbe53c1-b7ab-4689-b256-7090727b7ab3")]
            public virtual RepoItemInfo TwotabsearchtextboxInfo
            {
                get
                {
                    return _twotabsearchtextboxInfo;
                }
            }

            /// <summary>
            /// The Kurta item.
            /// </summary>
            [RepositoryItem("985e4747-43fd-4c76-a194-08518ca9ee50")]
            public virtual Ranorex.DivTag Kurta
            {
                get
                {
                    return _kurtaInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Kurta item info.
            /// </summary>
            [RepositoryItemInfo("985e4747-43fd-4c76-a194-08518ca9ee50")]
            public virtual RepoItemInfo KurtaInfo
            {
                get
                {
                    return _kurtaInfo;
                }
            }
        }

        /// <summary>
        /// The HowToWriteCodeInCHashRanorexGooAppFolder folder.
        /// </summary>
        [RepositoryFolder("657363ab-15e2-480e-b3bc-12236e49e9b4")]
        public partial class HowToWriteCodeInCHashRanorexGooAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _newtabInfo;
            RepoItemInfo _addressandsearchbarInfo;
            RepoItemInfo _paneInfo;

            /// <summary>
            /// Creates a new HowToWriteCodeInCHashRanorexGoo  folder.
            /// </summary>
            public HowToWriteCodeInCHashRanorexGooAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HowToWriteCodeInCHashRanorexGoo", "/form[@title>'how to write code in c# ranorex']", parentFolder, 30000, null, true, "657363ab-15e2-480e-b3bc-12236e49e9b4", "")
            {
                _newtabInfo = new RepoItemInfo(this, "NewTab", "container[@accessiblename>'how to write code in c# ranorex']/container[@accessiblename='Google Chrome']/container[2]/container[1]//button[@accessiblename='New Tab']", 30000, null, "0e69c50c-6fcd-47eb-a832-8700ad5a05f5");
                _addressandsearchbarInfo = new RepoItemInfo(this, "AddressAndSearchBar", "container[@accessiblename='New Tab - Google Chrome']/container[@accessiblename='Google Chrome']//container[@accessiblerole='Grouping']/text[@accessiblename='Address and search bar']", 30000, null, "6499289a-a843-4ac9-b2b6-facf7f6416aa");
                _paneInfo = new RepoItemInfo(this, "Pane", "container[@accessiblename>'Online Shopping site in India:']/container//list/?/?/container", 30000, null, "f96f4bca-cdfa-49fe-a18e-2ea8ab9983fb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("657363ab-15e2-480e-b3bc-12236e49e9b4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("657363ab-15e2-480e-b3bc-12236e49e9b4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NewTab item.
            /// </summary>
            [RepositoryItem("0e69c50c-6fcd-47eb-a832-8700ad5a05f5")]
            public virtual Ranorex.Button NewTab
            {
                get
                {
                    return _newtabInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NewTab item info.
            /// </summary>
            [RepositoryItemInfo("0e69c50c-6fcd-47eb-a832-8700ad5a05f5")]
            public virtual RepoItemInfo NewTabInfo
            {
                get
                {
                    return _newtabInfo;
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item.
            /// </summary>
            [RepositoryItem("6499289a-a843-4ac9-b2b6-facf7f6416aa")]
            public virtual Ranorex.Text AddressAndSearchBar
            {
                get
                {
                    return _addressandsearchbarInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The AddressAndSearchBar item info.
            /// </summary>
            [RepositoryItemInfo("6499289a-a843-4ac9-b2b6-facf7f6416aa")]
            public virtual RepoItemInfo AddressAndSearchBarInfo
            {
                get
                {
                    return _addressandsearchbarInfo;
                }
            }

            /// <summary>
            /// The Pane item.
            /// </summary>
            [RepositoryItem("f96f4bca-cdfa-49fe-a18e-2ea8ab9983fb")]
            public virtual Ranorex.Container Pane
            {
                get
                {
                    return _paneInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Pane item info.
            /// </summary>
            [RepositoryItemInfo("f96f4bca-cdfa-49fe-a18e-2ea8ab9983fb")]
            public virtual RepoItemInfo PaneInfo
            {
                get
                {
                    return _paneInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
