///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("316c9510-5171-4d41-a714-be67b2ea212e", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HowToWriteCodeInCHashRanorexGoo.NewTab' at 28;18.", repo.HowToWriteCodeInCHashRanorexGoo.NewTabInfo, new RecordItemIndex(0));
            repo.HowToWriteCodeInCHashRanorexGoo.NewTab.Click("28;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HowToWriteCodeInCHashRanorexGoo.AddressAndSearchBar' at 827;13.", repo.HowToWriteCodeInCHashRanorexGoo.AddressAndSearchBarInfo, new RecordItemIndex(1));
            repo.HowToWriteCodeInCHashRanorexGoo.AddressAndSearchBar.Click("827;13");
            Delay.Milliseconds(0);
            
            Key_sequence_AddressAndSearchBar(repo.HowToWriteCodeInCHashRanorexGoo.AddressAndSearchBarInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HowToWriteCodeInCHashRanorexGoo.Pane' at 1076;108.", repo.HowToWriteCodeInCHashRanorexGoo.PaneInfo, new RecordItemIndex(3));
            repo.HowToWriteCodeInCHashRanorexGoo.Pane.Click("1076;108");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ApEmail' at 45;15.", repo.ApplicationUnderTest.ApEmailInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.ApEmail.Click("45;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '9711591105' with focus on 'ApplicationUnderTest.ApEmail'.", repo.ApplicationUnderTest.ApEmailInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.ApEmail.PressKeys("9711591105");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Continue' at 135;19.", repo.ApplicationUnderTest.ContinueInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Continue.Click("135;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest' at 644;206.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Self.Click("644;206");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Shopping{RShiftKey down}@{RShiftKey up}4321' with focus on 'ApplicationUnderTest'.", repo.ApplicationUnderTest.SelfInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Self.EnsureVisible();
            Keyboard.Press("Shopping{RShiftKey down}@{RShiftKey up}4321");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SignInSubmit' at 173;10.", repo.ApplicationUnderTest.SignInSubmitInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.SignInSubmit.Click("173;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ApplicationUnderTest.AAlertContainerABoxInner'.", repo.ApplicationUnderTest.AAlertContainerABoxInnerInfo, new RecordItemIndex(10));
            Validate.Exists(repo.ApplicationUnderTest.AAlertContainerABoxInnerInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ApPassword' at 41;15.", repo.ApplicationUnderTest.ApPasswordInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.ApPassword.Click("41;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'asssss' with focus on 'ApplicationUnderTest.ApPassword'.", repo.ApplicationUnderTest.ApPasswordInfo, new RecordItemIndex(12));
            repo.ApplicationUnderTest.ApPassword.PressKeys("asssss");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SignInSubmit' at 157;13.", repo.ApplicationUnderTest.SignInSubmitInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.SignInSubmit.Click("157;13");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
